#!/bin/sh

#
#MIT License
#
#Copyright (c) 2022 Zapomnij
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.
#

set -e

machineid() {
	[ -f /etc/machine-id ] && rm /etc/machine-id
	[ -f /var/lib/dbus/machine-id ] && rm -rf /var/lib/dbus/machine-id
	mkdir -p /var/lib/dbus

	set +e
	[ -x /usr/bin/dbus-uuidgen ] && dbus-uuidgen --ensure
	set -e
}

case "${1}" in
	start)
		if [ -f /run/dbus.pid ]; then
			echo "dbus has already been started" > /dev/stderr
			exit 1
		fi
		machineid

		mkdir -p /run/dbus
		vinit-daemonutil -n dbus -S dbus-daemon -- --system --nofork
		;;
	stop)
		if [ ! -f /run/dbus.pid ]; then
			echo "dbus isn't running" > /dev/stderr
			exit 1
		fi
		set +e
		vinit-daemonutil -X dbus
		set -e

		rm -rf /run/dbus
		;;
	restart)
		${0} stop
		${0} start
		;;
	reload)
		if [ ! -f /run/dbus.pid ]; then
			echo "dbus isn't running" > /dev/stderr
			exit 1
		fi
		machineid
		set +e
		dbus-send --print-reply --system --type=method_call --dest=org.freedesktop.DBus / org.freedesktop.DBus.ReloadConfig
		;;
esac