#!/bin/sh

#
#MIT License
#
#Copyright (c) 2022 Zapomnij
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.
#
set -e

case "${1}" in
	start)
		if ! vinit-daemonutil -C dbus > /dev/null; then
			echo "	-> starting dbus"
			/etc/rc.d/dbus start
		fi
		if vinit-daemonutil -C elogind > /dev/null; then
			echo "elogind has already started" > /dev/stderr
			exit 1
		fi
		vinit-daemonutil -n elogind -S /lib/elogind/elogind
		;;
	stop)
		if ! vinit-daemonutil -C elogind > /dev/null; then
			echo "elogind isn't running" > /dev/stderr
			exit 1
		fi
		
		vinit-daemonutil -X elogind
		;;
	restart)
		${0} stop
		${0} start
		;;
esac