#!/bin/sh

#
#MIT License
#
#Copyright (c) 2022 Zapomnij
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.
#

set -e

[ -x /etc/rc.conf.d/lightdm.conf ] && . /etc/rc.conf.d/lightdm.conf

case "${1}" in
	start)
		vinit-daemonutil -n lightdm -S vinit-logger -- -L /var/log/services/lightdm.log lightdm -- ${LIGHTDM_OPTS}
		;;
	stop)
		vinit-daemonutil -X lightdm
		;;
	status)
		if vinit-daemonutil -C lightdm > /dev/null 2>&1; then
			echo "lightdm is running"
		else
			echo "lightdm isn't running"
		fi
		;;
	restart)
		${0} stop
		${1} start
		;;
esac